# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  node: circleci/node@4.7
  # aws-cli: circleci/aws-cli/1.23.4
  eb: circleci/aws-elastic-beanstalk@2.0.1

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  sample: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      build:
        docker:
          - image: "cimg/base:stable"
        executor: node/default
        steps:
          - node/install
          - checkout
          - aws-cli/setup
          - eb/setup
          - run:
              command: |
                npm run backend:install
          - run:
              command: |
                npm run backend:build
          - run:
              command: |
                npm run backend:deploy
          - run:
              command: |
                npm run frontend:install
          - run:
              command: |
                npm run frontend:build
          - run:
              command: |
                npm run frontend:deploy
    workflows:
      udagram:
        jobs:
          - build:
            filter:
              branches:
                only:
                  - master
